import nhanVienRoutes from "./nhanVienRoutes.js";
import leavePhep from "./leavePhepRoutes.js";
import maReportCashPlanningRoutes from "./maReportCashPlanningRoutes.js";
import maReportEquityRoutes from "./maReportEquityRoutes.js";
import maReportProfitLossASRoutes from "./maReportProfitLossASRoutes.js";
import maReportProfitLossHLRoutes from "./maReportProfitLossHLRoutes.js";
import maReportingWorkingCapital from "./maReportingWorkingCapitalRoutes.js";
import maReportProfitLossHvaV3Routes from "./maReportProfitLossHvaV3Routes.js";
import maReportProfitLossHvaV2Routes from "./maReportProfitLossHvaV2Routes.js";
import maReportProfitLossHvaV1Routes from "./maReportProfitLossHvaV1Routes.js";
import cfrContentRoutes from "./cfrContentRoutes.js";
import cfrProcessRoutes from "./cfrProcessRoutes.js";
import clientManagerRoutes from "./clientManagerRoutes.js";
import paymentRequestRoutes from "./paymentRequestRoutes.js";
import productListRoutes from "./productListRoutes.js";
import cashAccountRoutes from "./cashAccountRoutes.js";
import contractListRoutes from "./contractListRoutes.js";
import projectListRoutes from "./projectListRoutes.js";
import contractDetailRoutes from "./contractDetailRoutes.js";
import divisionListRoutes from "./divisionListRoutes.js";
import reportingLineRoutes from "./reportingLineRoutes.js";
import supplierListRoutes from "./supplierListRoutes.js";
import taskManagerRoutes from "./taskManagerRoutes.js";
import teamListRoutes from "./teamListRoutes.js";
import vasAccountListRoutes from "./vasAccountListRoutes.js";
import invoiceListRoutes from "./invoiceListRoutes.js";
import invoiceDetailRoutes from "./invoiceDetailRoutes.js";
import industryListRoutes from "./industryListRoutes.js";
import kmfKmnsListRoutes from "./kmfKmnsListRoutes.js";
import accountingJournalRoutes from "./accountingJournalRoutes.js";
import accountingJournalContractListRoutes from "./accountingJournalContractListRoutes.js";
import accountingJournalInvoiceListRoutes from "./accountingJournalInvoiceListRoutes.js";
import accountingJournalProductListRoutes from "./accountingJournalProductListRoutes.js";

export const allRouter = (app) => {
    app.use("/api/nhan-vien", nhanVienRoutes);
    app.use("/api/leave-phep", leavePhep);
    app.use("/api/client-manager", clientManagerRoutes);
    app.use("/api/ma-report-cash-planning", maReportCashPlanningRoutes);
    app.use("/api/ma-report-equity", maReportEquityRoutes);
    app.use("/api/ma-report-profit-loss-as", maReportProfitLossASRoutes);
    app.use("/api/ma-report-profit-loss-hl", maReportProfitLossHLRoutes);
    app.use("/api/ma-reporting-working-capital",maReportingWorkingCapital);
    app.use("/api/ma-reporting-profit-loss-hva-v3",maReportProfitLossHvaV3Routes);
    app.use("/api/ma-reporting-profit-loss-hva-v2",maReportProfitLossHvaV2Routes);
    app.use("/api/ma-reporting-profit-loss-hva-v1",maReportProfitLossHvaV1Routes);
    app.use("/api/cash-account",cashAccountRoutes);
    app.use("/api/cfr-content",cfrContentRoutes);
    app.use("/api/cfr-process",cfrProcessRoutes);
    app.use("/api/contract-list",contractListRoutes);
    app.use("/api/contract-detail",contractDetailRoutes);
    app.use("/api/division-list",divisionListRoutes);
    app.use("/api/industry-list",industryListRoutes);
    app.use("/api/kmf-kmns-list",kmfKmnsListRoutes);
    app.use("/api/payment-request",paymentRequestRoutes);
    app.use("/api/product-list",productListRoutes);
    app.use("/api/project-list",projectListRoutes);
    app.use("/api/reporting-line",reportingLineRoutes);
    app.use("/api/supplier-list",supplierListRoutes);
    app.use("/api/task-manager",taskManagerRoutes);
    app.use("/api/team-list",teamListRoutes);
    app.use("/api/vas-account-list",vasAccountListRoutes);
    app.use("/api/invoice-list",invoiceListRoutes);
    app.use("/api/invoice-detail",invoiceDetailRoutes);
    app.use("/api/accounting-journal",accountingJournalRoutes);
    app.use("/api/accounting-journal-contract-list",accountingJournalContractListRoutes);
    app.use("/api/accounting-journal-invoice-list",accountingJournalInvoiceListRoutes);
    app.use("/api/accounting-journal-product-list",accountingJournalProductListRoutes);

};